site_name: DevOps
site_author: niqdev
repo_url: https://github.com/niqdev/devops
theme: readthedocs
google_analytics: ['UA-68888222-4', 'niqdev.github.io']

nav:
    - Home: index.md
    - Linux: linux.md
    - Docker: docker.md
    - Ansible: ansible.md
    - Cassandra: cassandra.md
    - ZooKeeper: zookeeper.md
    - Kafka: kafka.md
    - Hadoop: hadoop.md
    - Kubernetes: kubernetes.md
    - System Design: system-design.md
    - Other: other.md
    - JVM (OLD): jvm.md
    - Scala (OLD): scala.md

# disable search plugin
#plugins: []
